services:
  api1: # API - Instância 01
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    mem_limit: 500m
    cpus: "0.25"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret

  api2: # API - Instância 02
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api2
    depends_on:
      - db
    expose:
      - "80"
    mem_limit: 500m
    cpus: "0.25"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    mem_limit: 500m
    cpus: "0.25"

  db: # Banco de dados
    image: postgres:latest
    mem_limit: 1500m
    cpus: "0.75"
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"


